services:
  sandbox:
    build:
      context: .
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ../../dist:/app/dist:ro
      - ../../node_modules:/app/node_modules:ro
      - ../../package.json:/app/package.json:ro