import type { Model, ProviderDef } from "../types.ts"

// Provider id constants — single source of truth for provider identifiers,
// referenced by both PROVIDERS and every entry in MODELS.
export const PROVIDER = {
	glm: "glm",
	gemini: "gemini",
	deepseek: "deepseek",
	openai: "openai",
	anthropic: "anthropic",
} as const

export const PROVIDERS: ProviderDef[] = [
	{
		id: PROVIDER.glm,
		name: "GLM (Z.AI)",
		apiFormat: "openai",
		baseUrl: "https://api.z.ai/api/coding/paas/v4",
		envKey: "GLM_API_KEY",
	},
	{
		id: PROVIDER.gemini,
		name: "Gemini (Google)",
		apiFormat: "gemini",
		baseUrl: "https://generativelanguage.googleapis.com",
		envKey: "GEMINI_API_KEY",
	},
	{
		id: PROVIDER.deepseek,
		name: "DeepSeek",
		apiFormat: "openai",
		baseUrl: "https://api.deepseek.com",
		envKey: "DEEPSEEK_API_KEY",
	},
	{
		id: PROVIDER.openai,
		name: "OpenAI",
		apiFormat: "openai",
		baseUrl: "https://api.openai.com/v1",
		envKey: "OPENAI_API_KEY",
	},
	{
		id: PROVIDER.anthropic,
		name: "Anthropic",
		apiFormat: "anthropic",
		baseUrl: "https://api.anthropic.com",
		envKey: "ANTHROPIC_API_KEY",
	},
]

export const MODELS: Model[] = [
	// GLM
	{
		id: "glm-5.1",
		name: "GLM-5.1",
		provider: PROVIDER.glm,
		contextWindow: 128_000,
		maxTokens: 4096,
		supportsThinking: false,
		default: true,
	},
	{
		id: "glm-5",
		name: "GLM-5",
		provider: PROVIDER.glm,
		contextWindow: 128_000,
		maxTokens: 4096,
		supportsThinking: false,
	},
	{
		id: "glm-5-turbo",
		name: "GLM-5 Turbo",
		provider: PROVIDER.glm,
		contextWindow: 128_000,
		maxTokens: 4096,
		supportsThinking: false,
	},
	{
		id: "glm-4.7",
		name: "GLM-4.7",
		provider: PROVIDER.glm,
		contextWindow: 128_000,
		maxTokens: 4096,
		supportsThinking: false,
	},
	{
		id: "glm-4.7-flash",
		name: "GLM-4.7 Flash (Free)",
		provider: PROVIDER.glm,
		contextWindow: 128_000,
		maxTokens: 4096,
		supportsThinking: false,
	},
	{
		id: "glm-4.5-flash",
		name: "GLM-4.5 Flash (Free)",
		provider: PROVIDER.glm,
		contextWindow: 128_000,
		maxTokens: 4096,
		supportsThinking: false,
	},
	// Gemini
	{
		id: "gemini-3.5-flash",
		name: "Gemini 3.5 Flash",
		provider: PROVIDER.gemini,
		contextWindow: 1_000_000,
		maxTokens: 65_536,
		supportsThinking: true,
		default: true,
	},
	{
		id: "gemini-3.1-pro-preview",
		name: "Gemini 3.1 Pro Preview",
		provider: PROVIDER.gemini,
		contextWindow: 2_000_000,
		maxTokens: 65_536,
		supportsThinking: true,
	},
	{
		id: "gemini-3.1-pro-preview-customtools",
		name: "Gemini 3.1 Pro (Custom Tools)",
		provider: PROVIDER.gemini,
		contextWindow: 2_000_000,
		maxTokens: 65_536,
		supportsThinking: true,
	},
	{
		id: "gemini-3.1-flash-lite",
		name: "Gemini 3.1 Flash-Lite",
		provider: PROVIDER.gemini,
		contextWindow: 1_000_000,
		maxTokens: 65_536,
		supportsThinking: true,
	},
	{
		id: "gemini-3.1-flash-lite-preview",
		name: "Gemini 3.1 Flash-Lite Preview",
		provider: PROVIDER.gemini,
		contextWindow: 1_000_000,
		maxTokens: 65_536,
		supportsThinking: true,
	},
	{
		id: "gemini-3-flash-preview",
		name: "Gemini 3 Flash Preview",
		provider: PROVIDER.gemini,
		contextWindow: 1_000_000,
		maxTokens: 65_536,
		supportsThinking: true,
	},
	{
		id: "gemini-2.5-pro",
		name: "Gemini 2.5 Pro",
		provider: PROVIDER.gemini,
		contextWindow: 2_000_000,
		maxTokens: 65_536,
		supportsThinking: false,
	},
	{
		id: "gemini-2.5-flash",
		name: "Gemini 2.5 Flash",
		provider: PROVIDER.gemini,
		contextWindow: 1_000_000,
		maxTokens: 65_536,
		supportsThinking: false,
	},
	{
		id: "gemini-2.5-flash-lite",
		name: "Gemini 2.5 Flash-Lite",
		provider: PROVIDER.gemini,
		contextWindow: 1_000_000,
		maxTokens: 65_536,
		supportsThinking: false,
	},
	{
		id: "gemini-2.5-computer-use-preview-10-2025",
		name: "Gemini 2.5 Computer Use",
		provider: PROVIDER.gemini,
		contextWindow: 1_000_000,
		maxTokens: 65_536,
		supportsThinking: false,
	},
	// DeepSeek
	{
		id: "deepseek-v4-flash",
		name: "DeepSeek V4 Flash",
		provider: PROVIDER.deepseek,
		contextWindow: 1_000_000,
		maxTokens: 16_384,
		supportsThinking: true,
		default: true,
	},
	{
		id: "deepseek-v4-pro",
		name: "DeepSeek V4 Pro",
		provider: PROVIDER.deepseek,
		contextWindow: 1_000_000,
		maxTokens: 16_384,
		supportsThinking: true,
	},
	// OpenAI
	{
		id: "gpt-5.5",
		name: "GPT-5.5",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "high",
		default: true,
	},
	{
		id: "gpt-5.5-pro",
		name: "GPT-5.5 Pro",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "xhigh",
	},
	{
		id: "gpt-5.4",
		name: "GPT-5.4",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "high",
	},
	{
		id: "gpt-5.4-pro",
		name: "GPT-5.4 Pro",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "xhigh",
	},
	{
		id: "gpt-5.4-mini",
		name: "GPT-5.4 Mini",
		provider: PROVIDER.openai,
		contextWindow: 400_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "medium",
	},
	{
		id: "gpt-5.4-nano",
		name: "GPT-5.4 Nano",
		provider: PROVIDER.openai,
		contextWindow: 400_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "low",
	},
	{
		id: "gpt-5.2",
		name: "GPT-5.2",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "high",
	},
	{
		id: "gpt-5.2-pro",
		name: "GPT-5.2 Pro",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "xhigh",
	},
	{
		id: "gpt-5.1",
		name: "GPT-5.1",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "high",
	},
	{
		id: "gpt-5",
		name: "GPT-5",
		provider: PROVIDER.openai,
		contextWindow: 400_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "medium",
	},
	{
		id: "gpt-5-mini",
		name: "GPT-5 Mini",
		provider: PROVIDER.openai,
		contextWindow: 400_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "medium",
	},
	{
		id: "gpt-5-nano",
		name: "GPT-5 Nano",
		provider: PROVIDER.openai,
		contextWindow: 400_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "low",
	},
	{
		id: "gpt-5-pro",
		name: "GPT-5 Pro",
		provider: PROVIDER.openai,
		contextWindow: 400_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "xhigh",
	},
	{
		id: "o4-mini",
		name: "o4 Mini",
		provider: PROVIDER.openai,
		contextWindow: 200_000,
		maxTokens: 100_000,
		supportsThinking: true,
		effort: "medium",
	},
	{
		id: "gpt-4.1",
		name: "GPT-4.1",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 32_768,
		supportsThinking: false,
	},
	{
		id: "gpt-4.1-mini",
		name: "GPT-4.1 Mini",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 32_768,
		supportsThinking: false,
	},
	{
		id: "gpt-4.1-nano",
		name: "GPT-4.1 Nano",
		provider: PROVIDER.openai,
		contextWindow: 1_000_000,
		maxTokens: 32_768,
		supportsThinking: false,
	},
	// Anthropic
	{
		id: "claude-fable-5",
		name: "Claude Fable 5",
		provider: PROVIDER.anthropic,
		contextWindow: 1_000_000,
		maxTokens: 128_000,
		supportsThinking: true,
		effort: "xhigh",
	},
	{
		id: "claude-opus-4-8",
		name: "Claude 4.8 Opus",
		provider: PROVIDER.anthropic,
		contextWindow: 200_000,
		maxTokens: 64_000,
		supportsThinking: true,
		effort: "xhigh",
		default: true,
	},
	{
		id: "claude-opus-4-7",
		name: "Claude 4.7 Opus",
		provider: PROVIDER.anthropic,
		contextWindow: 200_000,
		maxTokens: 64_000,
		supportsThinking: true,
		effort: "xhigh",
	},
	{
		id: "claude-opus-4-6",
		name: "Claude 4.6 Opus",
		provider: PROVIDER.anthropic,
		contextWindow: 200_000,
		maxTokens: 32_000,
		supportsThinking: true,
		effort: "high",
	},
	{
		id: "claude-opus-4-5",
		name: "Claude 4.5 Opus",
		provider: PROVIDER.anthropic,
		contextWindow: 200_000,
		maxTokens: 32_000,
		supportsThinking: true,
		effort: "high",
	},
	{
		id: "claude-sonnet-4-6",
		name: "Claude 4.6 Sonnet",
		provider: PROVIDER.anthropic,
		contextWindow: 200_000,
		maxTokens: 32_000,
		supportsThinking: true,
		effort: "medium",
	},
	{
		id: "claude-sonnet-4-5",
		name: "Claude 4.5 Sonnet",
		provider: PROVIDER.anthropic,
		contextWindow: 200_000,
		maxTokens: 32_000,
		supportsThinking: true,
		effort: "high",
	},
]

export function getProvider(id: string): ProviderDef | undefined {
	return PROVIDERS.find((p) => p.id === id)
}

export function getModelsForProvider(providerId: string): Model[] {
	return MODELS.filter((m) => m.provider === providerId)
}

// Returns a provider's default model (flagged default: true), falling back to
// the first listed model.
export function getDefaultModel(providerId: string): Model | undefined {
	const models = getModelsForProvider(providerId)
	return models.find((m) => m.default) ?? models[0]
}
